### ISSUE TITLE
Post CSS issues

### ISSUE THREAD

**Issue by a0m0rajab** [TimMikeladze/tsup-react-package-starter#117] opened 2024-03-11 20:11 UTC
Hi, when I tried to run this project based on the docs, I got this error: 

![image](https://github.com/TimMikeladze/tsup-react-package-starter/assets/18273833/32f8d9e1-725a-4e6d-8f55-36d035becff0)

```cmd
[0]
[0]   The plugin "postcss" was triggered by this import
[0]
[0]     src/Example.tsx:1:7:
[0]       1 │ import './Example.css';
[0]         ╵        ~~~~~~~~~~~~~~~
[0]
[0] DTS Build start
[0] ESM Build failed
[0] Error: Build failed with 1 error:
```

I think it's a postCSS issue, if that's the case it would be great to add the related command in the getting started code to make it clearer for people, or at least having a comment about it.

**Comment by TimMikeladze** [comment] 2024-03-11 21:55
Hi @a0m0rajab I'm not able to reproduce this. Can you provide a repository where I can reproduce this error?

I just tried running `pnpm build` on a fresh clone and install of this repository and everything worked fine. Are you sure you installed the packages?

**Comment by a0m0rajab** [comment] 2024-03-11 21:56
I did not do anything special just followed the documentation in the read me, I did not clone the repo yet I used degit

Sent from mobile device


________________________________

**Comment by TimMikeladze** [comment] 2024-03-11 22:21
degit clones the repo...

Did you run `pnpm install` afterwards?

**Comment by a0m0rajab** [comment] 2024-03-11 22:22
Yes I ran that

Sent from mobile device


________________________________

**Comment by TimMikeladze** [comment] 2024-03-11 22:32
Okay. You will need to provide a repo I can reproduce this error in.

**Comment by TimMikeladze** [comment] 2024-03-12 10:07
I’m closing this issue in the meantime. After you provide a reproduction repo, if it’s indeed a bug, I will reopen and fix it.

**Closed by TimMikeladze** 2024-03-12 10:07 UTC
